language: node_js
sudo: false
node_js:
  - node
install:
- npm install purescript@0.11.4 bower pulp purescript-psa -g
- bower install
script:
  - pulp build -- --censor-lib && pulp docs
  - bower link
  - cd example/ && bower -q link purescript-websocket-simple && bower -q install && npm install ws && pulp build -- --censor-lib && pulp run

after_success:
  - >-
    test $TRAVIS_TAG &&
    psc-publish > .pursuit.json &&
    curl -X POST https://pursuit.purescript.org/packages \
      -d @.pursuit.json \
      -H 'Accept: application/json' \
      -H "Authorization: token ${GITHUB_TOKEN}"
